image: gitlab.se.ifmo.ru:5050/dmitry/functional-programming/clojure

stages:
  - format
  - lint
  - test

format_check:
  stage: format
  script:
    - cljfmt check .
  rules:
    - when: always

lint_check:
  stage: lint
  script:
    - clj-kondo --lint ./*
  rules:
    - when: always

test_run:
  stage: test
  script:
    - cd lab1
    - clj -X:test
  rules:
    - when: always
